### ISSUE TITLE
How to run the project

### ISSUE THREAD

**Issue by rnrson9** [ingridnunes/bdi4jade#2]
I tried to run the code, but I didn't know how to compile and use it. Can the author add some tutorials to the readme on how to run this project, please?

**Comment by ingridnunes** [comment]
Dear rnrson9,

To run the examples of BDI4JADE, you can checkout the project in eclipse and follow the instructions in the "Running Examples in BDI4JADE" section of the readme.md file. I've reorganised the project recently  and renamed the project "examples-src" to "bdi4jade-examples", where you can find the class to execute as described in the documentation. I haven't updated the documentation accordingly yet.

If you want to execute the project without the code, you can get the jar files + dependencies as described in the "Download and Execution" section of the readme.md file, accessing the link that takes you to SourceForge.

The BDI4JADE jar files provided there are the same made available on the github release (https://github.com/ingridnunes/bdi4jade/releases/tag/v2.0). However, the dependencies are not provided there.

Thanks
Ingrid
