### ISSUE TITLE
Some questions on Reasoning cycle

### ISSUE THREAD

**Issue by FlavioFoxes** [ingridnunes/bdi4jade#3]
Good morning,
I'm Flavio. I need some clarifications about the reasoning cycle:
1. The reasoning cycle is a CyclicBehaviour, and the Plans are Behaviour. How do they co-exist? Are executed concurrently? Does the cycle wait all plans of the capabilities are completed?
2. There is a meta-level reasoning?
3. Is there a mechanism (during the execution of a plan) to handle sudden events in the environment? If yes, how it works?

Thank you in advance.
Flavio

**Comment by ingridnunes** [comment]
Hi Flavio,

1. The reasoning cycle is a CyclicBehaviour, and the Plans are Behaviour. How do they co-exist? Are executed concurrently? Does the cycle wait all plans of the capabilities are completed?

This is managed by Jade. The agent has different Behaviours (the reasoning cycle + active plans), and Jade is responsible for the scheduling.

2. There is a meta-level reasoning?

Yes, you can create instances of AgentReasoningStrategy and ReasoningStrategy (see their extensions, these are the super-interfaces) and set in the agent/capability.

3. Is there a mechanism (during the execution of a plan) to handle sudden events in the environment? If yes, how it works?

It depends how you implement it. If you implement the environment as an agent, then typically messages received will trigger a plan (see the ping pong example, which involves messages). Or you can somehow update beliefs not directly, but using the methods of the BeliefBase. In this case, you can add a listener to the BeliefBase, which based on changes on the belief base, goals are added to the agent (which will lead to the execution of plans).

Best,
Ingrid
